pipeline {
    agent any

    environment {
        SONAR_PROJECT_KEY = 'prodready-devops-platform'
        SONAR_HOST_URL = 'http://10.214.139.172:9000'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-ssh',
                    url: 'git@github.com:devopsbyammar/proready-devops-platform.git'
            }
        }

        stage('Unit Tests') {
            steps {
                sh '''
                    cd app
                    python3 -m venv .venv-jenkins
                    . .venv-jenkins/bin/activate
                    pip install -r requirements.txt
                    python -m pytest test_app.py -v
                '''
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    withCredentials([
                        string(
                            credentialsId: 'sonar-token',
                            variable: 'SONAR_TOKEN'
                        )
                    ]) {
                        sh '''
                            /opt/sonar-scanner/bin/sonar-scanner \
                              -Dproject.settings=sonarqube/sonar-project.properties \
                              -Dsonar.host.url=$SONAR_HOST_URL \
                              -Dsonar.token=$SONAR_TOKEN
                        '''
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                    docker build -t proready-app:${BUILD_NUMBER} ./app
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline completed successfully'
        }

        failure {
            echo '❌ Pipeline failed — check the stage logs'
        }
    }
}
